### ISSUE TITLE
In the project horizontal won't save scroll position

### ISSUE THREAD

**Issue by cylak** [mayoff/multiRowSnapper#1]
In the example if i scroll horizontal each rows to left or right in the first cell to another position, the fourth cell will also be at that same position.

Same for the second and the fifth, the third and the sixth... 

Is there a way for the horizontal scroll views in the cells to keep their position?

Thanks

**Comment by mayoff** [comment]
Store the collection view's scroll position along with your other data for that row, and restore it in `tableView:cellForRowAtIndexPath:`.

Since this is a toy project, there is no “other data for that row”, so there's no place to store the scroll position.

If you need more help, I recommend posting a question on stack overflow.
